### ISSUE TITLE
ImportError Cursor

### ISSUE THREAD

**Issue by TGihan** [RenanPalmeira/flask-blog#3]
i'm getting below error msg when run command ---  python manage_flask.py db init

$ python manage_flask.py db init
Traceback (most recent call last):
  File "manage_flask.py", line 3, in <module>
    import server
  File "G:\blog\flask-blog\server.py", line 5, in <module>
    from core.db import db, MongoDB_Connection, MongoDB_Models
  File "G:\blog\flask-blog\core\db.py", line 3, in <module>
    from mongokit import Connection, MongoClient
  File "C:\Python34\lib\site-packages\mongokit\__init__.py", line 31, in <module>
    from cursor import Cursor
ImportError: cannot import name 'Cursor'

before get this error i got cannot find module cursor but after install pip install cursor i'm getting this error. I'm a beginner to python and flask. Appreciate if you can give complete install guide with database setting change.

**Comment by RenanPalmeira** [comment]
Hi guy, first error maybe you don't have the MongoDB installed in your environment, but forget this because this project i not use more, you used Python 3.X and I wrote this project in Python 2.7 when i was learning to use Flask, today i use Flask just in API's, see the project has neither TDD :sweat:,  the last commit was 24 Feb 2015, I recommend this examples and websites for your first project Flask, see:

* http://flask.pocoo.org/docs/0.11/blueprints/
* http://flask.pocoo.org/docs/0.11/patterns/packages/
* https://www.digitalocean.com/community/tutorials/how-to-structure-large-flask-applications

Anyway i support this project in Python 3 today :v: https://github.com/RenanPalmeira/flask-blog/tree/python3

(Sorry if you not understood my english)

**Comment by AhmedAKhan** [comment]
was getting the same error, it looks like the error is because mongokit is dead, it does not support the newest version of pymongo 3 which automatically gets pulled down, thus giving the error

https://github.com/namlook/mongokit/issues/182
https://github.com/namlook/mongokit/issues/251
